project:
  type: website

website:
  title: "Martin Sterchi"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: about
        text: About
      - href: publications
        text: Publications
      - href: blog
        text: Blog
      - href: code
        text: Code
  page-footer: 
    left: "Copyright 2025, Martin Sterchi"
    background: primary

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

